JadeIT\CatalogDBundle\Entity\Item:
    type: entity
    table: null
    fields:
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: items
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: items
