parameters:
    jadeit.catalogd.event_subscriber.class: JadeIT\CatalogDBundle\Event\CatalogDSubscriber

services:
    event_subscriber:
        class: %jadeit.catalogd.event_subscriber.class%
        arguments:
            - @logger
        tags:
            - { name: monolog.logger, channel: catalogd }
